name: Go disgolink

on: [ push, pull_request ]

jobs:
    gobuild:
        # We want to run on external PRs, but not on our own internal PRs as they'll be run
        # by the push to the branch.
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Go
                uses: actions/setup-go@v2
                with:
                    go-version: 1.18

            -   name: go build
                run: cd disgolink && go build -v ./...

    govet:
        # We want to run on external PRs, but not on our own internal PRs as they'll be run
        # by the push to the branch.
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Go
                uses: actions/setup-go@v2
                with:
                    go-version: 1.18

            -   name: go vet
                run: cd disgolink && go vet -v ./...

    gotest:
        # We want to run on external PRs, but not on our own internal PRs as they'll be run
        # by the push to the branch.
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Go
                uses: actions/setup-go@v2
                with:
                    go-version: 1.18

            -   name: go test
                env:
                    token: ${{ secrets.TOKEN }}
                run: cd disgolink && go test -v ./...
